services:
  bhima:
    build: .
    image: thirdculturesoftware/bhima
    restart: unless-stopped
    ports:
      - "8080:${PORT:-8080}"
    environment:
      - REDIS_HOST=redis
      - DB_HOST=mysql
      - DB_USER=${DB_USER:-bhima_user}
      - DB_NAME=${DB_NAME:-bhima_db_name}
      - DB_PASS=${DB_PASS:-db_password}
    depends_on:
      - mysql
      - redis
    networks:
      - backend

  mysql:
    image: mysql:8.4
    restart: unless-stopped
    command:
      - --sql-mode=STRICT_ALL_TABLES,NO_UNSIGNED_SUBTRACTION
      - --mysql-native-password=ON
    volumes:
      - mysqldata:/var/lib/mysql/
      - ./server/models:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${DB_USER:-bhima_user}
      - MYSQL_DATABASE=${DB_NAME:-bhima_db_name}
      - MYSQL_PASSWORD=${DB_PASS:-db_password}
    networks:
      - backend

  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:

volumes:
  mysqldata:
